#!/usr/bin/env bash

release () {
    rm -rf dist
    npx webpack
    cp src/docs.html dist/
    npx surge dist cicada-notebook.surge.sh
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
